name: 'enhance-dependabot-PR-title'

on:
  pull_request_target:
    types: [assigned]

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  run:
    name: build
    runs-on: ubuntu-latest
    if: >
      contains(github.event.pull_request.labels.*.name, 'dependencies') &&
      !startsWith(${{ github.event.pull_request.title }}, 'chore(deps): ⬆️')
    steps:
      - name: Echo PR information
        run: |
          echo '[info] PR number: ${{ github.event.pull_request.number }}'
          echo '[info] PR title: ${{ github.event.pull_request.title }}'

      - name: Enhance PR title
        env:
          number: ${{ github.event.pull_request.number }}
          title: ${{ github.event.pull_request.title }}
        run: |
          gh pr edit ${{ env.number }} --title 'chore(deps): ⬆️ ${{ env.title }}'
