name: test

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'src/**'
      - 'locale/**'
      - tsconfig.json
  pull_request:
    paths:
      - 'src/**'
      - 'locale/**'
      - tsconfig.json

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [10, 12, 14, 15]
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2.3.4

      - name: Setup node
        uses: actions/setup-node@v2.2.0
        with:
          node-version: ${{ matrix.node }}

      - name: Setup package
        run: |
          node --version
          npm install

      - name: Run test and generate coverage
        run: npm run coverage

      - name: Upload coverage as artifact
        uses: actions/upload-artifact@v2.2.4
        with:
          name: coverage-${{ matrix.node }}
          path: coverage

      - name: Upload coverage to codecov
        uses: codecov/codecov-action@v2.0.1
        with:
          name: actions ${{ matrix.node }}
          fail_ci_if_error: true

      - name: Run lint-check
        run: npm run lint-check
